### ISSUE TITLE
Survivor/Monk Tracker

### ISSUE THREAD

**Issue by Axium1** [jaclynonacloud/rainworld-tracker#4]
Can you make a tracker that tracks the score for S/M?

**Comment by jaclynonacloud** [comment]
I can certainly look into it! 
What scores would you like tracked?  Similar to Hunter?

**Comment by Awesomegamer6566** [comment]
oops

**Comment by Axium1** [comment]
There is no score on Monk/Survivor, but this could be an unofficial score tracker. Instead of helping moon, when you meet her (with mark), it gives a score. The Monk would get less points for meeting FP (And more for kill-).

**Comment by Axium1** [comment]
Here's what the log would look like.
Food x 124 @ 1
124
Cycles survived x 20 @ 10
200
Deaths x 21 @ -3: -63
Quits x 3 @ -3: -9
Time x 12693 @ -1: -212
Met Moon x 100 @ 1
100
Met Five Pebbles x 40 @ 1
40
Ascended x 300 @ 1
300
Ranking
481
example kill(s)
Jet Fish kill(s) x 2 @ 4          8
Ranking : 489
**Five Pebbles** kill(s) x 1000 @ 1     1000
Ranking : JK
The Survivor x 2
978
The Outlaw x 3
1467
Ranking: 1467

**Comment by Axium1** [comment]
not sure if it tracks kills in monk/survivor runs though.

**Comment by Axium1** [comment]
Monk's score would be decreased by something like 100 for the non-kill things.

**Comment by jaclynonacloud** [comment]
This might be a little out of scope for this particular tracker, but the modding community might be interested in this!
I'll take a look into it when I can.

**Comment by Axium1** [comment]
Also, I looked at the creature atlas and it had a Slugcat on it. **How do you kill another Slugcat and why would you want to do that?**

**Comment by jaclynonacloud** [comment]
Haha slugcat has a score in the game so I added it to the score list. It's probably from arena mode.

**Comment by Axium1** [comment]
XD

**Comment by Axium1** [comment]
But I thought its default score is 0

**Comment by Awesomegamer6566** [comment]
Automaton would be op in arena (Can't be killed by contact)

**Comment by Axium1** [comment]
wait you can take a spear with you into the void sea, right?
