### ISSUE TITLE
Console or PC?

### ISSUE THREAD

**Issue by Axium1** [jaclynonacloud/rainworld-tracker#5]
Does this not work for PS4?

**Comment by jaclynonacloud** [comment]
This is PC only

**Comment by Axium1** [comment]
Hmm... how does the save check work? I could probably work around it.

**Comment by jaclynonacloud** [comment]
Currently the file is watched in the user's system and if a change in the file is detected, it will re-read the file.  It uses `fs.watchFile` to track these changes.  You'll need to see the electron branch for implementation.
